# Generated by Django 4.1.3 on 2022-11-06 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contry',
            new_name='country',
        ),
    ]
