# Generated by Django 4.1.3 on 2022-11-06 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_contacts_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact',
            new_name='chain_fk',
        ),
    ]
