# Generated by Django 4.1.3 on 2022-11-07 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_contact_contact_chain_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default=datetime.date(2022, 11, 7), verbose_name='relise date'),
        ),
    ]
