# Generated by Django 4.1.3 on 2022-11-07 19:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_alter_product_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chain',
            name='user',
        ),
        migrations.AddField(
            model_name='chain',
            name='staff',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
