# Generated by Django 4.1.3 on 2022-11-07 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_chain_user_chain_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 7, 19, 29, 3, 321618, tzinfo=datetime.timezone.utc), verbose_name='relise date'),
        ),
    ]
